/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'title' : string,
  'content' : string,
  'date' : Time,
  'category' : Category,
}
export type Category = { 'fee' : null } |
  { 'academic' : null } |
  { 'event' : null } |
  { 'general' : null };
export interface DocumentMetadata {
  'title' : string,
  'uploaderRole' : SchoolRole,
  'blob' : ExternalBlob,
  'category' : Category,
}
export interface ExamResult {
  'marks' : bigint,
  'subject' : string,
  'grade' : string,
  'student' : string,
}
export type ExternalBlob = Uint8Array;
export interface FeeRecord {
  'studentName' : string,
  'paid' : boolean,
  'dueDate' : Time,
  'amount' : bigint,
  'receiptNumber' : string,
}
export interface Homework {
  'subject' : string,
  'dueDate' : Time,
  'description' : string,
  'formClass' : string,
}
export type SchoolRole = { 'admin' : null } |
  { 'teacher' : null } |
  { 'reception' : null } |
  { 'studentParent' : null };
export interface StaffDirectoryEntry {
  'contact' : string,
  'name' : string,
  'subjectOrDepartment' : string,
}
export interface StudentDirectoryEntry {
  'parentContact' : string,
  'name' : string,
  'rollNumber' : bigint,
  'formClass' : string,
}
export type Time = bigint;
export interface TimetableEntry {
  'day' : string,
  'subject' : string,
  'teacher' : string,
  'formClass' : string,
  'timeSlot' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : SchoolRole,
  'classOrSubject' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitorLogEntry {
  'contact' : string,
  'host' : string,
  'name' : string,
  'checkInTime' : Time,
  'checkOutTime' : [] | [Time],
  'purpose' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDocument' : ActorMethod<
    [string, SchoolRole, ExternalBlob, Category],
    undefined
  >,
  'addExamResult' : ActorMethod<[string, string, bigint, string], undefined>,
  'addStaff' : ActorMethod<[string, string, string], undefined>,
  'addStudent' : ActorMethod<[string, string, bigint, string], undefined>,
  'addVisitor' : ActorMethod<[string, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkOutVisitor' : ActorMethod<[string], undefined>,
  'createAnnouncement' : ActorMethod<[string, string, Category], undefined>,
  'createFeeRecord' : ActorMethod<[string, bigint, Time, string], undefined>,
  'createHomework' : ActorMethod<[string, string, string, Time], undefined>,
  'createTimetableEntry' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllDocuments' : ActorMethod<[], Array<DocumentMetadata>>,
  'getAllStaff' : ActorMethod<[], Array<StaffDirectoryEntry>>,
  'getAllStudents' : ActorMethod<[], Array<StudentDirectoryEntry>>,
  'getAllVisitorLogs' : ActorMethod<[], Array<VisitorLogEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClassHomework' : ActorMethod<[string], Array<Homework>>,
  'getClassTimetable' : ActorMethod<[string], Array<TimetableEntry>>,
  'getDocumentsByCategory' : ActorMethod<[Category], Array<DocumentMetadata>>,
  'getStudentFeeRecords' : ActorMethod<[string], Array<FeeRecord>>,
  'getStudentResults' : ActorMethod<[string], Array<ExamResult>>,
  'getTeacherTimetable' : ActorMethod<[string], Array<TimetableEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markFeePaid' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];