/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SchoolRole = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'reception' : IDL.Null,
  'studentParent' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Variant({
  'fee' : IDL.Null,
  'academic' : IDL.Null,
  'event' : IDL.Null,
  'general' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'category' : Category,
});
export const DocumentMetadata = IDL.Record({
  'title' : IDL.Text,
  'uploaderRole' : SchoolRole,
  'blob' : ExternalBlob,
  'category' : Category,
});
export const StaffDirectoryEntry = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'subjectOrDepartment' : IDL.Text,
});
export const StudentDirectoryEntry = IDL.Record({
  'parentContact' : IDL.Text,
  'name' : IDL.Text,
  'rollNumber' : IDL.Nat,
  'formClass' : IDL.Text,
});
export const VisitorLogEntry = IDL.Record({
  'contact' : IDL.Text,
  'host' : IDL.Text,
  'name' : IDL.Text,
  'checkInTime' : Time,
  'checkOutTime' : IDL.Opt(Time),
  'purpose' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : SchoolRole,
  'classOrSubject' : IDL.Opt(IDL.Text),
});
export const Homework = IDL.Record({
  'subject' : IDL.Text,
  'dueDate' : Time,
  'description' : IDL.Text,
  'formClass' : IDL.Text,
});
export const TimetableEntry = IDL.Record({
  'day' : IDL.Text,
  'subject' : IDL.Text,
  'teacher' : IDL.Text,
  'formClass' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const FeeRecord = IDL.Record({
  'studentName' : IDL.Text,
  'paid' : IDL.Bool,
  'dueDate' : Time,
  'amount' : IDL.Nat,
  'receiptNumber' : IDL.Text,
});
export const ExamResult = IDL.Record({
  'marks' : IDL.Nat,
  'subject' : IDL.Text,
  'grade' : IDL.Text,
  'student' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDocument' : IDL.Func(
      [IDL.Text, SchoolRole, ExternalBlob, Category],
      [],
      [],
    ),
  'addExamResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addStaff' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addVisitor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkOutVisitor' : IDL.Func([IDL.Text], [], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text, Category], [], []),
  'createFeeRecord' : IDL.Func([IDL.Text, IDL.Nat, Time, IDL.Text], [], []),
  'createHomework' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [], []),
  'createTimetableEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllDocuments' : IDL.Func([], [IDL.Vec(DocumentMetadata)], ['query']),
  'getAllStaff' : IDL.Func([], [IDL.Vec(StaffDirectoryEntry)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(StudentDirectoryEntry)], ['query']),
  'getAllVisitorLogs' : IDL.Func([], [IDL.Vec(VisitorLogEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClassHomework' : IDL.Func([IDL.Text], [IDL.Vec(Homework)], ['query']),
  'getClassTimetable' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TimetableEntry)],
      ['query'],
    ),
  'getDocumentsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(DocumentMetadata)],
      ['query'],
    ),
  'getStudentFeeRecords' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FeeRecord)],
      ['query'],
    ),
  'getStudentResults' : IDL.Func([IDL.Text], [IDL.Vec(ExamResult)], ['query']),
  'getTeacherTimetable' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TimetableEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markFeePaid' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SchoolRole = IDL.Variant({
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'reception' : IDL.Null,
    'studentParent' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Variant({
    'fee' : IDL.Null,
    'academic' : IDL.Null,
    'event' : IDL.Null,
    'general' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'category' : Category,
  });
  const DocumentMetadata = IDL.Record({
    'title' : IDL.Text,
    'uploaderRole' : SchoolRole,
    'blob' : ExternalBlob,
    'category' : Category,
  });
  const StaffDirectoryEntry = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'subjectOrDepartment' : IDL.Text,
  });
  const StudentDirectoryEntry = IDL.Record({
    'parentContact' : IDL.Text,
    'name' : IDL.Text,
    'rollNumber' : IDL.Nat,
    'formClass' : IDL.Text,
  });
  const VisitorLogEntry = IDL.Record({
    'contact' : IDL.Text,
    'host' : IDL.Text,
    'name' : IDL.Text,
    'checkInTime' : Time,
    'checkOutTime' : IDL.Opt(Time),
    'purpose' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : SchoolRole,
    'classOrSubject' : IDL.Opt(IDL.Text),
  });
  const Homework = IDL.Record({
    'subject' : IDL.Text,
    'dueDate' : Time,
    'description' : IDL.Text,
    'formClass' : IDL.Text,
  });
  const TimetableEntry = IDL.Record({
    'day' : IDL.Text,
    'subject' : IDL.Text,
    'teacher' : IDL.Text,
    'formClass' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const FeeRecord = IDL.Record({
    'studentName' : IDL.Text,
    'paid' : IDL.Bool,
    'dueDate' : Time,
    'amount' : IDL.Nat,
    'receiptNumber' : IDL.Text,
  });
  const ExamResult = IDL.Record({
    'marks' : IDL.Nat,
    'subject' : IDL.Text,
    'grade' : IDL.Text,
    'student' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDocument' : IDL.Func(
        [IDL.Text, SchoolRole, ExternalBlob, Category],
        [],
        [],
      ),
    'addExamResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addStaff' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addVisitor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkOutVisitor' : IDL.Func([IDL.Text], [], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text, Category], [], []),
    'createFeeRecord' : IDL.Func([IDL.Text, IDL.Nat, Time, IDL.Text], [], []),
    'createHomework' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [], []),
    'createTimetableEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllDocuments' : IDL.Func([], [IDL.Vec(DocumentMetadata)], ['query']),
    'getAllStaff' : IDL.Func([], [IDL.Vec(StaffDirectoryEntry)], ['query']),
    'getAllStudents' : IDL.Func(
        [],
        [IDL.Vec(StudentDirectoryEntry)],
        ['query'],
      ),
    'getAllVisitorLogs' : IDL.Func([], [IDL.Vec(VisitorLogEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClassHomework' : IDL.Func([IDL.Text], [IDL.Vec(Homework)], ['query']),
    'getClassTimetable' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
    'getDocumentsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(DocumentMetadata)],
        ['query'],
      ),
    'getStudentFeeRecords' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FeeRecord)],
        ['query'],
      ),
    'getStudentResults' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExamResult)],
        ['query'],
      ),
    'getTeacherTimetable' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markFeePaid' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };